### ISSUE TITLE
About the way to load lisp libraries

### ISSUE THREAD

**Issue by t-cool** [marcoheisig/cl4py#1]
Hi, 

I'm trying to load libraries using quicklisp.

When I tried loading in this way, 
`lisp.eval("(ql:quickload :clack)")`

the following error occured.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/cl4py/lisp.py", line 44, in eval
    {'__init__': init})()
cl4py.lisp.SB-INT:SIMPLE-READER-PACKAGE-ERROR: Package QL does not exist.
```

Could you write the way to load lisp libraries in README.md?

**Comment by marcoheisig** [comment]
Hello t-cool,

first of all, thank you for being so brave as to use cl4py!  I wrote this library in just a few days and I hope it works for you.  I also intend to improve a lot of things about cl4py in 2019.

I just added a README entry regarding your problem.

Best regards,
Marco

**Comment by t-cool** [comment]
Hi Marco,
Thank you for telling me.
I'm looking forward to its updating!
