### ISSUE TITLE
Allow use others implementations than SBCL

### ISSUE THREAD

**Issue by noloop** [marcoheisig/cl4py#10]
Would be cool can use others implementations than SBCL, like ECL, and also can set the path to call the implementation binary.

**Comment by marcoheisig** [comment]
This should be possible by supplying an explicit `cmd` argument to the Lisp process constructor, like this:

```lisp
import cl4py
lisp = cl4py.Lisp(cmd=["ecl", "--load"])
```

If that (or something similar - I haven't tested the code snippet) doesn't work, feel free to submit a pull request.

**Comment by noloop** [comment]
It's working, thanks:

```python3
>>> import cl4py
>>> lisp = cl4py.Lisp(cmd=["ecl", "--load"])
>>> lisp.eval( ('+', 2, 3) )
5     
>>> lisp = cl4py.Lisp(cmd=["/home/user/Programs/ecl/ecl-host/bin/ecl", "--load"])
>>> lisp.eval( ('+', 2, 6) )
8
>>> 
```
