### ISSUE TITLE
Macros not available in cl4py

### ISSUE THREAD

**Issue by rpgoldman** [marcoheisig/cl4py#14]
I'm not sure why this is, but I just stumbled over it. I tried invoking a function (I thought) that was exported, but was actually a macro. I got errors about the function not being found.

And, indeed, when I look into `py.lisp`, I see this:

```
(defun package-contents-alist (package)
  (let ((alist '()))
    ;; Our trick to get from a Lisp-2 to a Lisp-1: functions take precedence.
    (loop for symbol being each external-symbol of package do
      (cond ((and (fboundp symbol)
                  (not (macro-function symbol))
                  (not (special-operator-p symbol)))
             (push (cons symbol (symbol-function symbol)) alist))
            ((and (boundp symbol)
                  (numberp (symbol-value symbol)))
             (push (cons symbol (symbol-value symbol)) alist))))
    alist))
```

Since lisp libraries often export functionality as macros, this is unfortunate. I guess it's because cl4py's Lisp eagerly evaluates its arguments?

This would at least be worth explaining in the README, and it would be nice if it could just be worked around. LMK if you have thoughts about how macros could be made available.

**Comment by marcoheisig** [comment]
Using macros has always been possible by calling `lisp.eval`.  But I just upgraded cl4py to export all macros in a package to Python. (c5abcb66d4b2d1520ec5fe8eba437092588605fe)

Example: `cl.loop('repeat', 10, 'collect', 42)` yields `List(42, 42, 42, 42, 42, 42, 42, 42, 42, 42)`
