### ISSUE TITLE
Can we assume ASDF/UIOP?

### ISSUE THREAD

**Issue by rpgoldman** [marcoheisig/cl4py#15]
If we can, it's easy to add backtraces.  If not, then we have to fight to set up an environment that is capable of loading `trivial-backtrace`.

Also, that would let us use `UIOP:QUIT`, which is more portable than `cl-user::quit`

**Comment by marcoheisig** [comment]
I don't think we should assume unconditionally assume UIOP.  But I added a mechanism that uses `uiop:quit` when possible (a9ffee388cf5d9fd6052ee2e85c55c51a7bdceff).
