### ISSUE TITLE
Wishlist: easier way to set variables

### ISSUE THREAD

**Issue by rpgoldman** [marcoheisig/cl4py#18]
Setting variables could use an easier interface, since it seems to mostly require use of `eval`, and at least some of the standard tools like `push` aren't available.

A way to look up variables might be nice.

**Comment by marcoheisig** [comment]
Fixed in 8f9fcb18aa6fd4a65689790cd68d647d4c41c81f.  The following code now works as expected:
```python
import cl4py;
lisp = cl4py.Lisp();
cl = lisp.find_package('CL')

cl.print_length
()

cl.print_length = 40
cl.print_length
40

cl.print_length = False
cl.print_length
()

cl.MOST_POSITIVE_DOUBLE_FLOAT
1.7976931348623157e+308
```
