### ISSUE TITLE
Small issues in README

### ISSUE THREAD

**Issue by Bike** [marcoheisig/cl4py#2]
```
>>> cl.oppd(5)
True
````
Probably supposed to be `oddp`?

```
>>> cl.remove(5, [1, 5, 2, 7, 5, 9])
[1, 2, 3, 4]
````
Probably you meant `[1, 2, 7, 9]`.

And this is even more minor, but feeding a circular list to `mapcar` is technically undefined - I don't know that any implementation will actually complain, though.

**Comment by marcoheisig** [comment]
Fixed.  Thanks for reporting!
