### ISSUE TITLE
Should we print readably?

### ISSUE THREAD

**Issue by rpgoldman** [marcoheisig/cl4py#20]
I encountered an issue where Lisp was returning a value that had two methods of printing -- readably and human-readably.

`py.lisp` doesn't control the dynamic variable `*print-readably*` in `pyprint-write`, but I believe it should.

To do so, we could wrap `(let ((*print-readably* t)) ...)` around the body of the `:around` method for `pyprint-write`.

I'll submit a PR for this, but would like to know your reaction to the idea.

**Comment by marcoheisig** [comment]
I think that makes sense.  The purpose of `pyprint-write` is definitely to produce readable text.

But I wonder what value triggers this behavior.  All values but those of a small number of built-in objects should be replaced by handles that can be printed readably.

Also, sorry for not replying to your other issue yet.  Right now, organizing ELS (plus my other duties) consumes most of my time.

**Comment by rpgoldman** [comment]
I have a function that returns a large s-expression, and one of the values buried in it has a `print-object` method that checks `*print-readably*` and if that is false, invokes `print-unreadable-object`.

... but I am having a hard time finding a MWE.

**Comment by marcoheisig** [comment]
Fixed in 10b338f3089f7aaa4c573caeacf12e6d2cd477bd.  As a bonus, I also found and fixed an obscure bug related to the printing of specialized strings.
