### ISSUE TITLE
Unbound variable error while loading .lisp file

### ISSUE THREAD

**Issue by craigkrais** [marcoheisig/cl4py#22]
In sbcl, I can load a file with 

`(load "/home/me/myfile.lisp")`

However when I try to run 

`lisp.eval(("load", "/home/me/myfile.lisp"))`

I encounter an unbound variable error for the path due to:

The variable CL4PY::/HOME/ME/MYFILE.LISP is unbound.

Here is the backtracking:

COMMON-LISP:UNBOUND-VARIABLE: 
#<UNBOUND-VARIABLE /HOME/ME/MYFILE.LISP {1002B58E73}>
  [condition]

Slots with :INSTANCE allocation:
  NAME                           = /HOME/ME/MYFILE.LISP
  NOT-YET-LOADED                 = NIL
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000560083}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {7FCE09C1EC6B}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {1002B5ADAB}> :PACKAGE :CL)
4: (UIOP/IMAGE:PRINT-CONDITION-BACKTRACE #<UNBOUND-VARIABLE /HOME/ME/MYFILE.LISP {1002B58E73}> :STREAM #<SB-IMPL::CHARACTER-STRING-OSTREAM {1002B5AC93}> :COUNT NIL)
5: (CL4PY:CL4PY)
6: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CL4PY:CL4PY) #<NULL-LEXENV>)
7: (SB-EXT:EVAL-TLF (CL4PY:CL4PY) 99 NIL)
8: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (CL4PY:CL4PY) 99)
9: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (CL4PY:CL4PY) :CURRENT-INDEX 99)
10: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {100183854B}> #<SB-C::SOURCE-INFO {1001838513}> SB-C::INPUT-ERROR-IN-LOAD)
11: (SB-INT:LOAD-AS-SOURCE #<SB-SYS:FD-STREAM for "file /home/me/anaconda3/lib/python3.8/site-packages/cl4py/py.lisp" {100182E843}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
12: ((FLET SB-FASL::THUNK :IN LOAD))
13: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7FCE09C1F69B}> #<SB-SYS:FD-STREAM for "file /home/me/anaconda3/lib/python3.8/site-packages/cl4py/py.lisp" {100182E843}>)
14: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-SYS:FD-STREAM for "file /home/me/anaconda3/lib/python3.8/site-packages/cl4py/py.lisp" {100182E843}> NIL)
15: (LOAD #<SB-SYS:FD-STREAM for "file /home/me/anaconda3/lib/python3.8/site-packages/cl4py/py.lisp" {100182E843}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
16: ((FLET SB-IMPL::LOAD-SCRIPT :IN SB-IMPL::PROCESS-SCRIPT) #<SB-SYS:FD-STREAM for "file /home/me/anaconda3/lib/python3.8/site-packages/cl4py/py.lisp" {100182E843}>)
17: ((FLET SB-UNIX::BODY :IN SB-IMPL::PROCESS-SCRIPT))
18: ((FLET "WITHOUT-INTERRUPTS-BODY-2" :IN SB-IMPL::PROCESS-SCRIPT))
19: (SB-IMPL::PROCESS-SCRIPT "/home/me/anaconda3/lib/python3.8/site-packages/cl4py/py.lisp")
20: (SB-IMPL::TOPLEVEL-INIT)
21: ((FLET SB-UNIX::BODY :IN SB-EXT:SAVE-LISP-AND-DIE))
22: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SB-EXT:SAVE-LISP-AND-DIE))
23: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))
Above backtrace due to this condition:
The variable CL4PY::/HOME/ME/MYFILE.LISP is unbound.

**Comment by marcoheisig** [comment]
For convenience, strings that appear directly inside of Python tuples are automatically converted to symbols (otherwise "load" wouldn't have worked either).  To avoid this behavior, you have to use something other than a Python tuple to denote a Lisp list.  So either

```lisp
lisp.eval(cl4py.List(cl4py.Symbol('LOAD'), "/home/me/myfile.lisp"))
```
or 
```lisp
lisp.eval(("load", cl4py.Quote("/home/me/myfile.lisp")))
```
or, my favorite
```lisp
cl = lisp.find_package("CL")
cl.load("/home/me/myfile.lisp")
```
I hope this helps.  Thanks for reporting, it tells me I probably should clarify this conversion process in the README.

**Comment by craigkrais** [comment]
Thank you for swift answer. 

While examining the source code I had found another way to do this:

`lisp.function('cl:load')("/home/me/myfile.lisp")`

but that still returned errors when functions defined inside the imported code was supposed to load using the given path.

`lisp.eval(("load", cl4py.Quote("/home/me/myfile.lisp")))`

This solves that issue as well.
