### ISSUE TITLE
Data race in LispWrapper's finalizer

### ISSUE THREAD

**Issue by Gleefre** [marcoheisig/cl4py#25]
Per the Python documentation:
> [`__del__()`](https://docs.python.org/3/reference/datamodel.html#object.__del__) can be invoked when arbitrary code is being executed, including from any arbitrary thread.

The finalizer of `LispWrapper` calls `self.lisp.eval`, which can occur during another call to `Lisp.eval`. This results in a data race involving the stdin/stdout streams, potentially causing undefined behavior. This can include errors or an infinite loop when reading the evaluation result.

In particular this can happen when reading a package object with a name collision (such as `compile_file_pathname` representing both the `*compile-file-pathname*` variable and the `compile-file-pathname` function in the CL package). In the `sharpsign_m` reader, a handle object is created and stored in the package attributes but is later overwritten by another object. This allows this object to be garbage collected by Python while the package is still being read, and for the finalizer to consume the closing parenthesis `)` at the end of the evaluation result list, causing the reader to hang waiting for the missing parenthesis.

Specifically, this issue appears to cause `lisp.find_package("CL")` to hang for SBCL versions from 2.3.0 to 2.4.2. This seems to be connected to the order in which `*compile-file-pathname*` and `compile-file-pathname` are listed in the package information.

**Comment by marcoheisig** [comment]
Wow, this is an excellent bug report!  Thanks for tracking this problem down.

Let me think about how to solve this...

Here is a suggestion: I introduce two methods for evaluation, `lisp.eval` for synchronous evaluation with return values, and `lisp.async_eval` for eventual evaluation with no results.  The `LispWrapper.__del__` method of  uses the latter.  Some kind of mutex or queue ensures that only one communication request runs at a time.

**Comment by Gleefre** [comment]
I have been thinking of a slightly different and maybe simpler solution -- to delay deletion until the next `Lisp.eval` call. (I'm opening PR only now because it took a bit too long to write the PR message...)

I think `async_eval` is just as good a solution though, and I don't really have a preference between these two.

**Comment by marcoheisig** [comment]
Let's go with your solution, it looks good to me.

**Comment by marcoheisig** [comment]
I just uploaded a new version of cl4py to PyPi.  Please let me know whether this fixes your problem.

**Comment by Gleefre** [comment]
Yep, this fixes the issue :) Thanks for the quick update!
