### ISSUE TITLE
Error when importing cl4py under windows 10

### ISSUE THREAD

**Issue by scorpion81** [marcoheisig/cl4py#6]
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cl4py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\cl4py\__init__.py", line 2, in <module>
    from .lisp import Lisp
  File "C:\Python37\lib\site-packages\cl4py\lisp.py", line 9, in <module>
    from .writer import lispify
  File "C:\Python37\lib\site-packages\cl4py\writer.py", line 136, in <module>
    numpy.float128 : lispify_float128,
  File "C:\Python37\lib\site-packages\numpy\__init__.py", line 220, in __getattr__
    "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'float128'

Seems numpy doesnt support float128 when being compiled with MSVC.
I commented a few offending lines (as hackfix) in reader.py, and writer.py, where numpy.float128 occurs. Not sure whats the proper fix here, besides switching over to Linux ;) . Maybe resort to numpy.float64 when using windows ?
I am using cl4py with sbcl 2.0 and python 3.7.4 and numpy 1.18 under windows 10.

**Comment by marcoheisig** [comment]
Hello @scorpion81, thanks for reporting.

Can you check whether f7e80da7ca8f8cc933c9d529336ee6774a3c7d49 fixes this issue for you?  (I don't have a Windows machine.)

If so, I will upload a new version of cl4py to pypi.

**Comment by scorpion81** [comment]
Hello @marcoheisig, thanks for your response :)  
This fix seems to atleast partially address the issue. Import works now.
But here https://github.com/marcoheisig/cl4py/blob/f7e80da7ca8f8cc933c9d529336ee6774a3c7d49/cl4py/reader.py#L186 numpy.float128 is being called as well. I dont have much experience with Lisp yet, so i am not sure when this is being called. But potentially this might be a source of error too under windows there.

**Comment by marcoheisig** [comment]
I just uploaded a new version to PyPi that should address all these issues.
