### ISSUE TITLE
Request for advice: Lisp Backtraces

### ISSUE THREAD

**Issue by rpgoldman** [marcoheisig/cl4py#8]
Any suggestions for debugging the interaction? E.g., I load up a bunch of configuration into my lisp session, and I'm getting errors in there.

I'd love to be able to dump a backtrace (probably with `trivial-backtrace`) at such a time -- has anyone done this?

Alternatively, has anyone figured out how to start up in swank, to attach and debug?

Thanks!

**Comment by marcoheisig** [comment]
Yes, I'd love to have nice backtraces, too.  The only problem is that I want cl4py to work without a Quicklisp installation,  so depending on `trivial-backtrace` is problematic.  Maybe I should add a mechanism for having such optional functionality.

I hope this is not too urgent, because I am very busy preparing the 1.0 version of Petalisp and I try hard not to get distracted by my side projects.  But this is something I could imagine working on during autumn or winter.

I have never used cl4py and swank together, so I can't give any advice about that.

**Comment by rpgoldman** [comment]
I could have a look at the backtrace issue, assuming that use of `trivial-backtrace` has to be optional.

But to do that, I would need a little help understanding the streams.  It seems like *everything* that the CL process writes, whether it's to `*error-output*` or `*standard-output*`, gets folded together into a single stream that flows to cl4py.  Is that right?  Is that what should happen? Or should we separate the two, so that `*error-output*` could be redirected to a console, or to a log file, depending on context?

Also, do you think if we added backtraces, we should just write them to a stream, or would it be better for the python side if we could serialize them in some more python-friendly manner? I really have no idea.

**Comment by marcoheisig** [comment]
At the moment, the Lisp streams `*standard-output*` and `*trace-output*` are combined and converted to a single Lisp string, which is then sent to Python together with the values of the most recently executed command.  On the Python side, this string is then printed to the standard output.  The `*error-output*` is currently not processed at all (if I remember correctly).

I agree it would be better to collect each Lisp stream into its own string and send those to Python.  Then Python could write everything that was sent to `*standard-output*` and `*trace-output*` to its standard output (but one after the other, without mixing them), and everything that was sent to `*error-output*` to its error output.

Alternatively, one could think about opening multiple streams from Python to Lisp.  But I haven't investigated that option so far.

About the backtraces - I think having them written to a stream would already help tremendously.  An integration into the Python debugging infrastructure (Is there such a thing?) would be wonderful, of course, but I think having a printed stacktrace at all is probably good enough.

**Comment by rpgoldman** [comment]
Just realized something: UIOP has portable backtracing in it, so we could use that instead of `trivial-backtrace`.

**Comment by marcoheisig** [comment]
Fixed in bfa2af403590e7d57621ee8b7ad27930a4800a31.
